name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        shell: cmd

      - name: Build
        run: cmake --build build
        shell: cmd

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: build/bin/NoTrackSwitcher.exe
